replicaCount: 2

image:
  repository: nginx
  tag: 1.21.0
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 80

serviceMonitor:
  enabled: true
  namespace: monitoring
  selector:
    app: nginx
  endpoints:
    - port: http
      path: /