replicaCount: 2

image:
  repository: nginx
  pullPolicy: IfNotPresent
  tag: stable

service:
  type: ClusterIP
  port: 80
  targetPort: 80

ingress:
  enabled: true
  annotations: {
    "kubernetes.io/ingress.class": "nginx"
  }
  hosts:
    - host: nginx.example.com
      paths:
        - path: /
          pathType: Prefix